version: "2"

services:
    web:
        build: .
        command: python -u serviceAgregation/server.py
        ports:
            - "5000:5000"
        container_name: agregation_web
        
    db:
        image: mongo
        ports:
            - "27018:27017"
        container_name: agregation_mongo
    
networks:
    default:
        external:
            name: bibliography-net